brickpiflask/brickpiblueprint.py
from flask import Flask, Blueprint, render_template, session, request, redirect, url_for, flash, jsonify, Response
from brickpiflask.yourrobot import *
from brickpiflask.interfaces.camerainterface import *
import helpers
from datetime import datetime
import globalvars


brickpiblueprint = Blueprint('brickpiblueprint', __name__, template_folder='templates', static_folder='static')

BRICKPI = globalvars.BRICKPI #ALIAS for globalvars.BRICKPI
DATABASE = globalvars.DATABASE #ALIAS for globalvars.DATABASE

# HTTPS REQUEST HANDERS RETURNING HTML ------------------------------------------
# homepage for the brickpi
@brickpiblueprint.route('/', methods=['GET','POST'])
def brickpihome():
    if 'userid' not in session: #userid hasnt logged in
        return redirect('../')   #need to use the dot to avoid redirecting da
    return render_template('brickpihome.html') 

# dashboard for the brickpi
@brickpiblueprint.route('/brickpidashboard', methods=['GET','POST'])
def brickpidashboard():
    if 'userid' not in session: #userid hasnt logged in
        return redirect('../')   #need to use the dot to avoid redirecting da
    enabled = (BRICKPI != None)
    return render_template('brickpidashboard.html', robotenabled=enabled) #hides or shows controls

#sensor view
@brickpiblueprint.route('/brickpisensorview', methods=['GET','POST'])
def brickpisensorview():
    if 'userid' not in session:
        return redirect('../')
    if not BRICKPI:
        return redirect('../brickpi/brickpidashboard')
    return render_template('brickpisensorview.html', data=BRICKPI.get_all_sensors()) 

# turtle demo
@brickpiblueprint.route('/brickpiturtle', methods=['GET','POST'])
def brickpiturtle():
    if 'userid' not in session: #userid hasnt logged in
        return redirect('../')   #need to use the dot to avoid redirecting data
    if request.method == "POST":
        pass
    return render_template('brickpiturtle.html')


# AJAX REQUEST HANDLERS RETURNING JSON ---------------------
# AJAX - load the brickpi
@brickpiblueprint.route('/brickpiload', methods=['GET','POST'])
def brickpiload():
    global BRICKPI
    if BRICKPI == None:
        BRICKPI = load_robot(20, globalvars.LOGGER)
        globalvars.BRICKPI = BRICKPI #update reference in global
        sensordict = "Not Loaded"
        if BRICKPI:
            bp = BRICKPI.BP #alias to shorten code
            motorports = {'rightmotor':bp.PORT_B, 'leftmotor':bp.PORT_C, 'mediummotor':bp.PORT_D }
            sensorports =  {'thermal':None, 'colour':bp.PORT_1,'ultra':bp.PORT_4,'imu':1 }
            BRICKPI.configure_sensors(motorports,sensorports) #should take 4 secs
            if BRICKPI.Configured:
                sensordict = BRICKPI.get_all_sensors()
    return jsonify({'message':"Brick Pi loaded. Sensor values = " + str(sensordict) })

# AJAX - shutdown the brickpi
@brickpiblueprint.route('/brickpishutdown', methods=['GET','POST'])
def brickpishutdown():
    global BRICKPI #you need to use global if you editing the value of the variable
    if BRICKPI:
        BRICKPI.CurrentRoutine = "stop"
        BRICKPI.safe_exit()
        BRICKPI = None
    return jsonify({'message':'Brick Pi shutting down'})

@brickpiblueprint.route('/brickpiautomate', methods=['GET','POST'])
def brickpiautomate():
    return jsonify({'message':'Automated searching'})

@brickpiblueprint.route('/brickpistart', methods=['GET','POST'])
def brickpistart():
    data = None
    return jsonify(data)  #python dictionary -> converted JSON

@brickpiblueprint.route('/brickpileft', methods=['GET','POST'])
def brickpileft():
    data = None
    return jsonify(data)  

@brickpiblueprint.route('/brickpiright', methods=['GET','POST'])
def brickpiright():
    data = None
    return jsonify(data)       

@brickpiblueprint.route('/brickpistop', methods=['GET','POST'])
def brickpistop():
    if BRICKPI:
        BRICKPI.CurrentRoutine = "stop"
        BRICKPI.stop_all()
    return jsonify({'message':'Stopping'})

@brickpiblueprint.route('/brickpishoot', methods=['GET','POST'])
def brickpishoot():
    return jsonify({'message':'Shooting'}) 

# CAMERA CODE (Not Sure how it works)
def gen(camera):
    """Video streaming generator function."""
    while True:
        frame = camera.get_frame()
        if frame:
            yield (b'--frame\r\n'
                    b'Content-Type: image/jpeg\r\n\r\n' + frame + b'\r\n') 

@brickpiblueprint.route('/videofeed')
def videofeed():
    """Video streaming route. Put this in the src attribute of an img tag."""
    return Response(gen(Camera()), mimetype='multipart/x-mixed-replace; boundary=frame') #not actually sure what this code does

brickpiflask/templates/brickpidashboard.html
{% extends "brickpilayout.html" %}

{% block newstyles %}
	<link href="https://cdn.jsdelivr.net/npm/jsxgraph@1.1.0/distrib/jsxgraph.css" />
{% endblock %}
{% block content %}
<div class="container-fluid">

	<h1>Dashboard</h1>
	<button id="loadbutton" type="button" class="btn btn-success" onclick="hideelement('loadbutton'); JSONrequest('brickpiload','POST',brickpiloadedhandler);">Load BrickPi</button>

	<div id="dashboard">
		<div class="row">
			<div id="map"><div id="box" class="jxgbox"></div></div>
			<div id="videofeed"><img src="{{ url_for('brickpiblueprint.videofeed') }}" width=100% ></div></div>
		<div class="row text-center fitrow">
			<div class="col-4">
				<button type="button" class="btn btn-success" onclick="JSONrequest('brickpistart','POST',forwardturtle)">Forward</button>
			</div>
			<div class="col-4">
				<button type="button" class="btn btn-danger" onclick="JSONrequest('brickpistop','POST',donothing)">Stop</button>
			</div>
			<div class="col-4">
				<button type="button" class="btn btn-dark" onclick="hideelement('dashboard'); JSONrequest('brickpishutdown','POST', brickpishutdownhandler);">Shutdown Robot</button>
			</div>
		</div>
		<div class="row text-center fitrow">
			<div class="col-4">
				<button type="button" class="btn btn-success" onclick="JSONrequest('brickpileft','POST',rotateturtle);">Turn Left</button>
			</div>
			<div class="col-4">
				<button type="button" class="btn btn-success" onclick="JSONrequest('brickpiright','POST',rotateturtle);"">Turn Right</button>
			</div>
			<div class="col-4">
				<button type="button" class="btn btn-primary" onclick="JSONrequest('brickpiautomate','POST');">Automate Search</button>
			</div>
		</div>
		<div class="row text-center fitrow">
			<div class="col-4">
				<button type="button" class="btn btn-warning" onclick="JSONrequest('brickpishoot','POST');">Shoot</button>
			</div>
		</div>
		<br/>
	</div>
	
</div>
{% endblock %}
{% block scripts %}
	{% if robotenabled %} <!-- cant equate because comes in as the word 'True'-->
		<script> robotenabled = true;</script>
	{% else %}
		<script> robotenabled = false;</script>
	{% endif %}
	<script src="https://cdn.jsdelivr.net/npm/jsxgraph@1.1.0/distrib/jsxgraphcore.js"></script>
	<script src="static/mapping.js"></script>
	<script src="static/brickpirequesthandlers.js"></script>
{% endblock %}

brickpiflask/templates/brickpihome.html
{% extends "brickpilayout.html" %}

{% block content %}
<div class="container">
    <h1>Brick Pi Home</h1>
    <p>Welcome to the Brick Pi Template. You can use this template to build the website interface to your robot.</p>
</div>
{% endblock %}

brickpiflask/templates/brickpilayout.html
{% extends "layout.html" %}

{% block styles %}
    <link rel="stylesheet" href="static/brickpi.css">
    {% block newstyles %}
    {% endblock %}
{% endblock %}

{% block menu %}
        <nav class="navbar navbar-expand-lg navbar navbar-dark bg-danger">
                <a href="/" class="navbar-brand">Flask Example</a>
                <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse2">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarCollapse2">
                    <div class="navbar-nav">
                        <a href="/brickpi/brickpidashboard" class="nav-item nav-link">Dashboard</a>
                        <a href="/brickpi/brickpisensorview" class="nav-item nav-link">Sensor View</a>
                        <a href="/brickpi/brickpiturtle" class="nav-item nav-link">Turtle</a>
                        <a href="/logoff" class="nav-item nav-link">Log Off</a>
                    </div>
                </div>
            </nav><br>
    {% endblock %}

brickpiflask/templates/brickpisensorview.html
{% extends "brickpilayout.html" %}

{% block content %}
<div class="container">
    <h1>Sensor View</h1>
    {% if data %}
    <table class="table">
        <thead><tr><th scope="col">Sensor</th><th scope="col">Value</th></tr></thead>
        <tbody>
            <tr><th scope="row">Battery</th><td id="sbattery">{{data['battery']}}</td><td>volts</td></tr>
            <tr><th scope="row">Colour</th><td id="scolour">{{data['colour']}}</td><td>-</td></tr>
            <tr><th scope="row">Ultrasonic</th><td id="sultrasonic">{{data['ultrasonic']}}</td><td>cm</td></tr>
            <tr><th scope="row">Thermal</th><td id="sthermal">{{data['thermal']}}</td><td>celsius</td></tr>
            <tr><th scope="row">Acceleration</th><td id="sacceleration">{{data['acceleration']}}</td><td>cm/s^2</td></tr>
            <tr><th scope="row">Compass</th><td id="scompass">{{data['compass']}}</td><td>degrees</td></tr>
            <tr><th scope="row">Gyro</th><td id="sgyro">{{data['gyro']}}</td><td>degrees/s^2</td></tr>
            <tr><th scope="row">Temperature</th><td id="stemperature">{{data['temperature']}}</td><td>Celsius</td></tr>
            <tr><th scope="row">Orientation</th><td id="sorientation">{{data['orientation']}}</td><td>units</td></tr>
        </tbody>
        </table>
        {% endif %}
</div>
{% endblock %}

brickpiflask/templates/brickpiturtle.html
{% extends "brickpilayout.html" %}

{% block styles %}
	<link href="https://cdn.jsdelivr.net/npm/jsxgraph@1.1.0/distrib/jsxgraph.css" />
{% endblock %}
{% block content %}
<div class="container">
	<h1>Javascript Turtle</h1>
	<p><a href="http://jsxgraph.org/wp/index.html">JSXgraph</a></p>
	<p>JSXGraph is a library of mathematical functions for drawing graphs etc. It includes a Javascript version of Python Turtle, which can be useful for drawing. The turtle script can be used to tell the turtle what to do.</p>
	<div id="box" class="jxgbox" style="width:500px; height:500px;"></div>
</div>
{% endblock %}
{% block scripts %}
	<script src="https://cdn.jsdelivr.net/npm/jsxgraph@1.1.0/distrib/jsxgraphcore.js"></script>
	<script src="static/turtleexample.js"></script>
{% endblock %}

brickpiflask/templates/index.html
{% extends "brickpilayout.html" %}

{% block content %}
<div class="container">
    <h1>brickpi Home</h1>
    <p>Welcome to the Brick Pi Template. You can use this template to build your website interface to your robot.</p>
</div>
{% endblock %}